### ISSUE TITLE
Upgrade Centos 7.9 to Centos-stream 8 via proxy serwer - problem

### ISSUE THREAD

**Issue by smurdza** [oamg/leapp#820] opened 2023-04-04 11:47 UTC
I have a problem with Upgrade Centos 7.9 to Centos-stream 8 via proxy serwer.
I set proxy in yum,conf any dnf.conf and I set LEAPP_PROXY_HOST=

But i have a below problem, after : leapp upgrade

STDERR:
No matches found for the following disable plugin patterns: subscription-manager
Repository extras is listed more than once in the configuration
Repository extras-source is listed more than once in the configuration
Warning: Package marked by Leapp to install not found in repositories metadata: python38-pulp-python rubygem-foreman-tasks-core python38-pulp-deb python38-pulp-certguard python3-javapackages python38-pulpcore python38-pulp-cli ivy-local python38-pulp-container rubygem-foreman_remote_execution_core python38-pulp-rpm log4j12 centos-linux-release python38-pulp-file
Warning: Package marked by Leapp to upgrade not found in repositories metadata: gpg-pubkey
Error: Error downloading packages:
  Curl error (7): Couldn't connect to server for http://mirrorlist.centos.org/?release=8-stream&arch=x86_64&repo=BaseOS [Failed to connect to mirrorlist.centos.org port 80: Connection refused]

How can I resolve this problem ?

**Comment by Rezney** [comment] 2023-04-04 12:59
@smurdza Hello, thank you for reaching out. Please note that Leapp itself is a framework that enables you to define a workflow which will, consequently, help you to upgrade or modernize your system. However defining and implementing the workflow is up to the user.

You can take a look here for inspiration:

`https://github.com/oamg/leapp-repository/tree/master/repos/system_upgrade`

The above is the repository containing workflow to upgrade RHEL systems (supported by Red Hat). Unfortunately, I am not aware of any supported way to get from CentOS to CentOS Stream. One can convert from CentOS 7 to RHEL 7 and subsequently upgrade to RHEL 8 in a supported way though.

With your permission, I would close this issue as not a BUG.

Thank you for your understanding.

**Comment by smurdza** [comment] 2023-04-04 13:12
Ok, thank you for respond.

**Closed as completed** 2023-04-04 14:09 UTC
Labels: bug
