### ISSUE TITLE
Allow actor message dependencies within a phase

### ISSUE THREAD

**Issue by bocekm** [oamg/leapp#491] opened 2019-04-14 13:33 UTC
## Actual behavior
Leapp framework tells me that it can't solve dependency between actors even though it should be able to solve it.

### Original state:
![RpmTransactionTasks_problem_orig](https://user-images.githubusercontent.com/9884110/56093439-68fe4b00-5eb8-11e9-9844-b3f4770086f3.png)

### State in which Leapp should be able to solve dependency order:
![RpmTransactionTasks_problem](https://user-images.githubusercontent.com/9884110/56093440-70255900-5eb8-11e9-9ffd-179857c0b8fa.png)

**To Reproduce**
Steps to reproduce the behavior
1. install leapp and leapp-repository
1. consume RpmTransactionTasks in PesEventsScanner
3. run leapp upgrade --debug
4. See error:
```
2019-04-05 09:18:00.445 DEBUG    PID: 636 leapp.repository.system_upgrade_el7toel8: Loading workflow modules
leapp.exceptions.CyclingDependenciesError: Could not solve dependency order for 'pes_events_scanner'
```

**Expected behavior**
There's no cycle within a phase. So I would expect Leapp to solve the order this way:

Facts Phase:
1. TransactionWorkarounds and RpmTransactionConfigTasksCollector (the order does not matter)
2. PesEventsScanner

Checks Phase:
1. SCTPChecks
2. FilterRpmTransactionTasks

**Comment by vinzenz** [comment] 2019-04-15 16:18
Isn’t the problem that the peseventscanner produces the same message it consumes? In this case this cannot work and is the reason for the error.

**Comment by bocekm** [comment] 2019-04-15 16:41
Yes, it produces message of the same model as it consumes. I don't think that should be disallowed. The dependency order is possible to "calculate". In this case there's no cyclic dependency.

**Comment by vinzenz** [comment] 2019-04-16 08:25
No this is not a bug and a won't fix and indeed this is not as easy as you suggest. There was a deliberate design decision not to allow this, because the algorithm cannot know when the message should be scheduled.

Consider these 4 actors:
<img src="https://user-images.githubusercontent.com/36638/56192850-98839380-602f-11e9-9b96-97aea821483b.png" width=300>

You end up with something like this:
<img src="https://user-images.githubusercontent.com/36638/56193702-8c003a80-6031-11e9-9d1a-0246ff3c2413.png" width=300>

Now if I would do as you said, how would I now prioritize either Actor1 or Actor2?

If you want to solve this, let the PES data produce a different message and let the consumer of that message consume that as well.

**Closed by vinzenz** 2019-04-16 08:25 UTC
Labels: bug
